const threads = new Map();

function createDefaultThread() {
  const threadId = "demo-thread-001";
  threads.set(threadId, {
    thread_id: threadId,
    values: {
      title: "Demo Chat",
      messages: [],
      artifacts: [],
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  });
}

createDefaultThread();

function getThread(threadId) {
  return threads.get(threadId);
}

function createThread(values = {}) {
  const threadId = `thread-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`;
  const now = new Date().toISOString();
  const thread = {
    thread_id: threadId,
    values: {
      title: values.title || "New Chat",
      messages: values.messages || [],
      artifacts: values.artifacts || [],
    },
    created_at: now,
    updated_at: now,
  };
  threads.set(threadId, thread);
  return thread;
}

function updateThread(threadId, values) {
  const thread = threads.get(threadId);
  if (!thread) return undefined;
  thread.values = { ...thread.values, ...values };
  thread.updated_at = new Date().toISOString();
  return thread;
}

function getThreadHistory(threadId, limit = 10) {
  const thread = threads.get(threadId);
  if (!thread) return [];
  const messages = thread.values.messages || [];
  return messages.slice(-limit);
}

function searchThreads(params = {}) {
  const limit = params.limit || 50;
  const offset = params.offset || 0;
  const threadList = Array.from(threads.values());
  threadList.sort(
    (a, b) => new Date(b.updated_at).getTime() - new Date(a.updated_at).getTime()
  );
  return threadList.slice(offset, offset + limit);
}

function deleteThread(threadId) {
  return threads.delete(threadId);
}

function parseBody(req) {
  return new Promise((resolve) => {
    let body = "";
    req.on("data", (chunk) => (body += chunk));
    req.on("end", () => {
      try {
        resolve(body ? JSON.parse(body) : {});
      } catch {
        resolve({});
      }
    });
  });
}

function sendJSON(res, status, data) {
  res.writeHead(status, { "Content-Type": "application/json" });
  res.end(JSON.stringify(data));
}

function sendSSE(res, event, data, id) {
  let sseData = "";
  sseData += `event: ${event}\n`;
  if (id) sseData += `id: ${id}\n`;
  sseData += `data: ${JSON.stringify(data)}\n\n`;
  res.write(sseData);
}

async function handleThreadSearch(req, res) {
  const body = await parseBody(req);
  const result = searchThreads({
    limit: body.limit,
    offset: body.offset,
    sortBy: body.sortBy,
    sortOrder: body.sortOrder,
  });
  sendJSON(res, 200, result);
}

async function handleThreadHistory(req, res, threadId) {
  const body = await parseBody(req);
  const limit = body.limit ?? 10;
  const history = getThreadHistory(threadId, limit);
  sendJSON(res, 200, history);
}

async function handleThreadCreate(req, res) {
  const body = await parseBody(req);
  const thread = createThread(body.values);
  sendJSON(res, 201, thread);
}

function handleThreadGet(req, res, threadId) {
  if (req.method !== "GET") {
    res.writeHead(405, { Allow: "GET" });
    res.end();
    return;
  }
  const thread = getThread(threadId);
  if (!thread) {
    sendJSON(res, 404, { error: "Thread not found" });
    return;
  }
  sendJSON(res, 200, thread);
}

function handleThreadDelete(req, res, threadId) {
  if (req.method !== "DELETE") {
    res.writeHead(405, { Allow: "DELETE" });
    res.end();
    return;
  }
  const deleted = deleteThread(threadId);
  if (!deleted) {
    sendJSON(res, 404, { error: "Thread not found" });
    return;
  }
  res.writeHead(204);
  res.end();
}

async function handleThreadState(req, res, threadId) {
  if (req.method === "GET") {
    const thread = getThread(threadId);
    if (!thread) {
      sendJSON(res, 404, { error: "Thread not found" });
      return;
    }
    sendJSON(res, 200, { values: thread.values });
  } else if (req.method === "POST") {
    const body = await parseBody(req);
    const thread = updateThread(threadId, body.values);
    if (!thread) {
      sendJSON(res, 404, { error: "Thread not found" });
      return;
    }
    sendJSON(res, 200, { values: thread.values });
  } else {
    res.writeHead(405, { Allow: "GET, POST" });
    res.end();
  }
}

const MOCK_RESPONSES = [
  "This is a mock AI response generated by the mock server. The LangGraph SDK is working correctly!",
  "I'm a simulated AI assistant running on the mock server. Everything looks good!",
  "Mock server is functioning properly. Your chat demo is set up correctly.",
];

async function handleRunsStream(req, res, threadId) {
  res.writeHead(200, {
    "Content-Type": "text/event-stream",
    "Cache-Control": "no-cache",
    Connection: "keep-alive",
    "X-Accel-Buffering": "no",
  });

  let body = {};
  try {
    body = await parseBody(req);
  } catch (e) {
    // ignore
  }

  const input = body.input || {};
  const messages = input.messages || [];
  const lastHuman = [...messages].reverse().find((m) => m.type === "human");
  let userText = "Hello";
  if (Array.isArray(lastHuman?.content) && lastHuman.content.length > 0) {
    const first = lastHuman.content[0];
    if (first && typeof first === "object" && "text" in first) {
      userText = String(first.text);
    }
  }

  const runId = `mock-run-${Date.now()}`;

  sendSSE(res, "metadata", {
    run_id: runId,
    thread_id: threadId,
    assistant_id: "lead_agent",
  });

  let responseText = MOCK_RESPONSES[0];
  if (userText.toLowerCase().includes("hello")) {
    responseText = "Hello! I'm a mock AI assistant. How can I help you today?";
  } else if (userText.toLowerCase().includes("help")) {
    responseText = "I'm here to help! This is a mock response from the development server.";
  } else if (userText.length > 50) {
    responseText = `I received your message: "${userText.slice(0, 50)}...". This is a mock response showing that the streaming infrastructure is working correctly.`;
  }

  const words = responseText.split("");
  let index = 0;
  const msgId = `mock-msg-${Date.now()}`;

  function sendChunk() {
    if (index < words.length) {
      sendSSE(
        res,
        "messages",
        [
          {
            type: "ai",
            id: msgId,
            content: words.slice(0, index + 1).join(""),
          },
          { langgraph_checkpoint_ns: "main" }
        ],
        String(index)
      );
      index++;
      setTimeout(sendChunk, 30);
    } else {
      sendSSE(res, "end", { status: "complete" });
      res.end();
    }
  }

  setTimeout(sendChunk, 100);

  req.on("close", () => {
    res.end();
  });
}

function setupMockServer(app) {
  app.post("/mock/api/threads/search", (req, res) => handleThreadSearch(req, res));
  app.post("/mock/api/threads", (req, res) => handleThreadCreate(req, res));
  app.get("/mock/api/threads/:threadId", (req, res) => handleThreadGet(req, res, req.params.threadId));
  app.delete("/mock/api/threads/:threadId", (req, res) => handleThreadDelete(req, res, req.params.threadId));
  app.post("/mock/api/threads/:threadId/history", (req, res) => handleThreadHistory(req, res, req.params.threadId));
  app.get("/mock/api/threads/:threadId/state", (req, res) => handleThreadState(req, res, req.params.threadId));
  app.post("/mock/api/threads/:threadId/state", (req, res) => handleThreadState(req, res, req.params.threadId));
  app.post("/mock/api/threads/:threadId/runs/stream", (req, res) => handleRunsStream(req, res, req.params.threadId));

  console.log("[Mock Server] Registered /mock/api routes");
}

module.exports = { setupMockServer };
