function parseBody(req) {
  return new Promise((resolve) => {
    let body = "";
    req.on("data", (chunk) => (body += chunk));
    req.on("end", () => {
      try {
        resolve(body ? JSON.parse(body) : {});
      } catch {
        resolve({});
      }
    });
  });
}

function sendSSE(res, event, data, id) {
  let sseData = "";
  sseData += `event: ${event}\n`;
  if (id) sseData += `id: ${id}\n`;
  sseData += `data: ${JSON.stringify(data)}\n\n`;
  res.write(sseData);
}

const MOCK_RESPONSES = [
  "This is a mock AI response generated by the mock server. The LangGraph SDK is working correctly!",
  "I'm a simulated AI assistant running on the mock server. Everything looks good!",
  "Mock server is functioning properly. Your chat demo is set up correctly.",
];

// POST /mock/api/threads/{threadId}/runs/stream
async function handleRunsStream(req, res, threadId) {
  res.writeHead(200, {
    "Content-Type": "text/event-stream",
    "Cache-Control": "no-cache",
    Connection: "keep-alive",
    "X-Accel-Buffering": "no",
  });

  let body = {};
  try {
    body = await parseBody(req);
  } catch (e) {
    // ignore
  }

  const input = body.input || {};
  const messages = input.messages || [];
  const lastHuman = [...messages].reverse().find((m) => m.type === "human");
  let userText = "Hello";
  if (Array.isArray(lastHuman?.content) && lastHuman.content.length > 0) {
    const first = lastHuman.content[0];
    if (first && typeof first === "object" && "text" in first) {
      userText = String(first.text);
    }
  }

  const runId = `mock-run-${Date.now()}`;

  sendSSE(res, "metadata", {
    run_id: runId,
    thread_id: threadId,
    assistant_id: "lead_agent",
  });

  let responseText = MOCK_RESPONSES[0];
  if (userText.toLowerCase().includes("hello")) {
    responseText = "Hello! I'm a mock AI assistant. How can I help you today?";
  } else if (userText.toLowerCase().includes("help")) {
    responseText = "I'm here to help! This is a mock response from the development server.";
  } else if (userText.length > 50) {
    responseText = `I received your message: "${userText.slice(0, 50)}...". This is a mock response showing that the streaming infrastructure is working correctly.`;
  }

  const words = responseText.split("");
  let index = 0;

  function sendChunk() {
    if (index < words.length) {
      sendSSE(
        res,
        "values",
        {
          messages: [
            {
              type: "ai",
              id: `mock-msg-${Date.now()}`,
              content: words.slice(0, index + 1).join(""),
            },
          ],
        },
        String(index)
      );
      index++;
      setTimeout(sendChunk, 30);
    } else {
      sendSSE(res, "end", { status: "complete" });
      res.end();
    }
  }

  setTimeout(sendChunk, 100);

  req.on("close", () => {
    res.end();
  });
}

module.exports = { handleRunsStream };
